[Inductor] Skip illegal launch grid values as 'inf' during autotune
Summary:
### Issue
When generating auto-tuning configs, we do max grid size check only using size_hitns.

However, when running the auto-tuning code, we generate kernel inputs that could be much larger than size hints.

We need autotune code runtime guard against the max grid size over flow as well.

### Fix
- generate a runtime check for grid sizes, throw customized error when overflowing
- relying on existing invalid config capture + skip logic to not crash the autotune process, hence lifting up the substr into `INVALID_CONFIG_ERR_SUBSTR` to make it more maintainable
- also centrialize the usage of max grid sizes into a common constant

Test Plan:
Failure repro: https://www.internalfb.com/intern/testinfra/testrun/25614222898236081

```
OverflowError: signed integer is greater than maximum
```

- passed new unit test
- internal use case resolved
- OSS CI

Differential Revision: D103032505